name: Test, Credo

on: [push, release]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-elixir@v1
        with:
          version-file: ".tool-versions"
          version-type: "strict"

      - name: Deps get and check unused
        run: mix deps.get && mix deps.unlock --check-unused

      - name: Check Credo
        run: mix credo --strict

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Run Tests
        run: mix do test
